const suppliers=["Minh An Phát","SG Tân Sơn","Kim Phúc"];
const products=[
 {name:"Bàn phím máy vi tính",code:"IT-BA00001",request:"PR-2511-00001",category:"Thiết bị CNTT",spec:"Bàn phím có dây USB",qty:35,unit:"Cái",offers:[offer(0,5696000),offer(1,5696000),offer(2,5696000)]},
 {name:"Chuột gaming có dây",code:"IT-BA00002",request:"PR-2511-00002",category:"Thiết bị CNTT",spec:"Cảm biến 6400 DPI, đèn LED",qty:35,unit:"Cái",offers:[offer(0,2360000),offer(1,3250000),offer(2,4200000)]},
 {name:"Pin Laptop HP 11.1V",code:"IT-BA00003",request:"PR-2511-00003",category:"Thiết bị CNTT",spec:"6 cell, 4400mAh, 11.1V",qty:35,unit:"Cái",offers:[offer(0,12500000),offer(1,2450000),offer(2,9896000)]}
];
function offer(i,price){return{name:suppliers[i],price,vat:10,offerQty:10,warranty:"Chưa cung cấp"}}
const money=n=>new Intl.NumberFormat("vi-VN").format(Math.round(n));
const state={product:0,alloc:{},productFilter:"all",productQuery:"",supplierQuery:""};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const rows=Array.from({length:15},(_,i)=>({id:`SSP-2511-${String(i+1).padStart(5,"0")}`,content:i%2?"Bổ sung thiết bị phục vụ vận hành khối văn phòng":"Khối CNS đề xuất mua thiết bị cấp phát cho nhân sự mới",status:i%4===1?"Nháp":i%4===2?"Đã duyệt":"Chờ duyệt"}));

function renderRequests(query=""){$("#requestRows").innerHTML=rows.filter(r=>(r.id+r.content).toLowerCase().includes(query.toLowerCase())).map(r=>`<tr><td><button class="link open-detail">${r.id}</button></td><td><span class="count">+3</span></td><td><span class="count">+3</span></td><td>Sevago</td><td>${r.content}</td><td>05/11/2025 14:46</td><td>[03920] - Trần Minh Tuấn</td><td><span class="status">${r.status}</span></td><td class="actions"><button class="open-detail">◉</button><button>✎</button><button>♲</button></td></tr>`).join("");$$('.open-detail').forEach(b=>b.onclick=openDetail)}
function openDetail(){$("#listPage").classList.add("hidden");$("#detailPage").classList.remove("hidden")}
function closeDetail(){$("#detailPage").classList.add("hidden");$("#listPage").classList.remove("hidden")}

function selectedQty(pi){return Object.values(state.alloc[pi]||{}).reduce((a,b)=>a+b,0)}
function filteredProducts(){return products.map((p,i)=>({...p,index:i,selected:selectedQty(i)})).filter(p=>(state.productFilter==="all"||(state.productFilter==="open"&&p.selected<p.qty)||(state.productFilter==="done"&&p.selected===p.qty))&&(p.name+p.code).toLowerCase().includes(state.productQuery.toLowerCase()))}
function renderProductList(){$("#productList").innerHTML=filteredProducts().map(p=>`<button class="product-item ${state.product===p.index?'active':''}" data-index="${p.index}"><span>${p.index+1}</span><span><b>${p.name}</b><small>${p.code} · ${p.qty} ${p.unit}</small><em class="${p.selected===p.qty?'done':''}">${p.selected===0?'Chưa phân bổ':p.selected===p.qty?`Đã đủ ${p.qty}/${p.qty}`:`Đã phân bổ ${p.selected}/${p.qty}`}</em></span></button>`).join("");$$('.product-item').forEach(b=>b.onclick=()=>{state.product=Number(b.dataset.index);renderCompare()})}
function currentProduct(){return products[state.product]}
function totalAfterVat(o){return o.price*o.offerQty*(1+o.vat/100)}
function setQty(si,value){const p=currentProduct(),max=p.offers[si].offerQty;state.alloc[state.product]??={};state.alloc[state.product][si]=Math.max(0,Math.min(Number(value)||0,max));renderCompare()}
function chooseMax(si){const p=currentProduct(),current=(state.alloc[state.product]||{})[si]||0,allocated=selectedQty(state.product),left=Math.max(0,p.qty-(allocated-current)),qty=Math.min(p.offers[si].offerQty,left);setQty(si,qty);toast(qty===p.offers[si].offerQty?`Đã chọn tối đa ${qty} ${p.unit} từ ${p.offers[si].name}.`:`Đã chọn ${qty} ${p.unit} để đủ số lượng đề nghị.`)}
function renderCompare(){const p=currentProduct(),allocation=state.alloc[state.product]||{},allocated=selectedQty(state.product),remaining=p.qty-allocated,status=allocated===0?'empty':allocated<p.qty?'short':allocated===p.qty?'complete':'over';renderProductList();$("#productHeader").innerHTML=`<div><span>Sản phẩm ${state.product+1} trong ${products.length}</span><h3>${p.name}</h3><small>${p.code} · Cần mua ${p.qty} ${p.unit} · ${p.spec}</small></div><div><small>Mã đề nghị</small><b>${p.request}</b></div><div><small>Danh mục</small><b>${p.category}</b></div>`;
 const visible=p.offers.map((o,i)=>({...o,index:i,total:totalAfterVat(o)})).filter(o=>o.name.toLowerCase().includes(state.supplierQuery.toLowerCase())).sort((a,b)=>a.total-b.total),low=Math.min(...visible.map(o=>o.total));$("#supplierCount").textContent=`${visible.length} nhà cung cấp đã báo giá`;
 $("#supplierRows").innerHTML=visible.map(o=>{const qty=allocation[o.index]||0,diff=o.total-low,pct=low?diff/low*100:0;return`<tr class="${qty?'chosen':''}"><td class="supplier-name"><b>${o.name}</b><button class="show-supplier" data-index="${o.index}">Xem chi tiết</button></td><td>${money(o.price)} ₫</td><td>${o.vat}%</td><td><strong>${money(o.total)} ₫</strong></td><td><div class="difference ${diff===0?'low':'high'}">${diff===0?'Thấp nhất':`<b>+${money(diff)} ₫</b><small>Cao hơn ${pct.toFixed(1)}%</small>`}</div></td><td><b>${o.offerQty} ${p.unit}</b></td><td><div class="qty-box"><button data-action="minus" data-index="${o.index}">−</button><input data-index="${o.index}" type="number" min="0" max="${o.offerQty}" value="${qty||''}" placeholder="0"><button data-action="plus" data-index="${o.index}">+</button></div><button class="max-btn" data-index="${o.index}" ${qty===o.offerQty?'disabled':''}>${qty===o.offerQty?'Đã chọn tối đa':'Chọn tối đa'}</button></td></tr>`}).join("");
 $$('[data-action="minus"]').forEach(b=>b.onclick=()=>setQty(+b.dataset.index,(allocation[b.dataset.index]||0)-1));$$('[data-action="plus"]').forEach(b=>b.onclick=()=>setQty(+b.dataset.index,(allocation[b.dataset.index]||0)+1));$$('.qty-box input').forEach(i=>i.onchange=()=>setQty(+i.dataset.index,+i.value));$$('.max-btn').forEach(b=>b.onclick=()=>chooseMax(+b.dataset.index));$$('.show-supplier').forEach(b=>b.onclick=()=>showSupplier(+b.dataset.index));
 $("#allocationStatus").className=`allocation-status ${status}`;$("#allocationStatus").innerHTML=`<span><b>${status==='empty'?'Chưa phân bổ số lượng':status==='short'?'Chưa đủ số lượng đề nghị':status==='complete'?'Đã phân bổ đủ số lượng':'Số lượng phân bổ đang vượt mức'}</b><small>Đã phân bổ ${allocated}/${p.qty} ${p.unit}${remaining>0?`. Còn ${remaining} ${p.unit}.`:remaining<0?`. Vượt ${Math.abs(remaining)} ${p.unit}.`:'.'}</small></span>`;$("#confirmAllocation").disabled=status!=="complete";
 const total=Object.entries(state.alloc).reduce((sum,[pi,a])=>sum+Object.entries(a).reduce((s,[si,q])=>s+products[pi].offers[si].price*(1+products[pi].offers[si].vat/100)*q,0),0);$("#grandTotal").textContent=`${money(total)} ₫`}
function suggest(){const p=currentProduct(),sorted=p.offers.map((o,i)=>({...o,i})).sort((a,b)=>a.price-b.price);let left=p.qty;state.alloc[state.product]={};sorted.forEach(o=>{const take=Math.min(left,o.offerQty);if(take)state.alloc[state.product][o.i]=take;left-=take});renderCompare();toast(left?`Đã chọn ${p.qty-left}/${p.qty} ${p.unit}. Còn thiếu ${left} ${p.unit}.`:`Đã chọn đủ theo giá thấp nhất.`)}
function showSupplier(si){const p=currentProduct(),o=p.offers[si],qty=(state.alloc[state.product]||{})[si]||0,fields=[["ĐVT NCC",p.unit],["Số lượng NCC báo",o.offerQty],["Số lượng đã chọn",qty],["Thời gian giao hàng","3 đến 5 ngày"],["Điều khoản thanh toán","Thanh toán ngay"],["Hình thức thanh toán","Chuyển khoản"],["Bảo hành",o.warranty],["Thông tin khác","Chưa cung cấp"]];$(".comparison-layout").classList.add("with-detail");$("#supplierDetail").classList.remove("hidden");$("#supplierDetail").innerHTML=`<header><div><small>Chi tiết nhà cung cấp</small><h3>${o.name}</h3></div><button class="plain" id="closeSupplier">×</button></header><div class="detail-price"><span>Thành tiền sau VAT</span><strong>${money(totalAfterVat(o))} ₫</strong><small>Đơn giá ${money(o.price)} ₫ · VAT ${o.vat}%</small></div>${fields.map(([a,b])=>`<div class="detail-row"><span>${a}</span><b>${b}</b></div>`).join('')}`;$("#closeSupplier").onclick=()=>{$("#supplierDetail").classList.add("hidden");$(".comparison-layout").classList.remove("with-detail")}}
function toast(text){const t=$("#toast");t.textContent=text;t.classList.remove("hidden");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.add("hidden"),3000)}
function openProductForm(){const sel=$("#sourceProduct");sel.innerHTML=products.map((p,i)=>`<option value="${i}">${p.code}</option>`).join('');updateProductForm();$("#formModal").classList.remove("hidden")}
function updateProductForm(){const p=products[+$("#sourceProduct").value||0];$("#sourceName").value=p.name;$("#supplierChecks").innerHTML=p.offers.map((o,i)=>`<label><input type="checkbox" name="supplier" value="${i}"><span><b>${o.name}</b><small>${money(totalAfterVat(o))} ₫ sau VAT</small></span></label>`).join('')}
function closeAll(selector){$$(selector).forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'))}

renderRequests();$("#reviewers").innerHTML=["Trần Thị Minh","Trần Đại Nghĩa","Hà Khánh Vân","Lê Quang Hải","Tô Hiếu Đức"].map((n,i)=>`<div class="reviewer"><i>${['TM','ĐN','KV','QH','ĐĐ'][i]}</i><div><b>[03920] - ${n}</b><small>${i===2?'Trưởng phòng ban':'Nhân viên thiết kế UI/UX'}</small></div></div>`).join('');
$("#requestSearch").oninput=e=>renderRequests(e.target.value);$("#backBtn").onclick=closeDetail;$("#openCompare").onclick=()=>{$("#compareModal").classList.remove("hidden");renderCompare()};$(".close-modal").onclick=()=>$("#compareModal").classList.add("hidden");$("#productSearch").oninput=e=>{state.productQuery=e.target.value;renderProductList()};$("#supplierSearch").oninput=e=>{state.supplierQuery=e.target.value;renderCompare()};$$('.filter-row button').forEach(b=>b.onclick=()=>{$$('.filter-row button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.productFilter=b.dataset.filter;renderProductList()});$("#suggestPrice").onclick=suggest;$("#confirmAllocation").onclick=()=>toast("Đã xác nhận phân bổ số lượng.");$("#addProductBtn").onclick=openProductForm;$("#sourceProduct").onchange=updateProductForm;closeAll('.close-form');closeAll('.close-price');$("#declarePrice").onclick=()=>$("#priceModal").classList.remove("hidden");
$("#productForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),src=products[+f.get('source')],chosen=f.getAll('supplier').map(Number);products.push({...src,request:f.get('request'),qty:+f.get('qty'),unit:f.get('unit'),offers:src.offers.filter((_,i)=>chosen.includes(i))});state.product=products.length-1;e.target.closest('.modal').classList.add('hidden');renderCompare();toast(`Đã thêm ${src.name}.`)};
$("#priceForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),p=currentProduct(),price=+f.get('price'),qty=+f.get('qty'),vat=+f.get('vat');p.offers.push({name:f.get('supplier'),price,offerQty:qty,vat,warranty:f.get('warranty')||'Chưa cung cấp'});e.target.reset();e.target.closest('.modal').classList.add('hidden');renderCompare();toast('Đã thêm báo giá nhà cung cấp.')} ;
